# Generated by Django 6.0.1 on 2026-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_attachment_file_name_attachment_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
