# Generated by Django 6.0.1 on 2026-03-26 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0006_remove_attachment_message_attachment_messages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='messages',
            new_name='message',
        ),
    ]
