# Generated by Django 6.0.1 on 2026-01-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='followers',
            new_name='followers_count',
        ),
        migrations.AddField(
            model_name='profiles',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='profiles.profiles'),
        ),
    ]
