# Generated by Django 6.0.1 on 2026-01-13 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rename_followers_profiles_followers_count_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='followers_count',
            new_name='followers',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='following',
        ),
    ]
