# Generated by Django 6.0.1 on 2026-01-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_followers_count_profiles_followers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='profiles.profiles'),
        ),
    ]
