# Generated by Django 6.0.1 on 2026-01-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('github_username', models.CharField(default='', max_length=256)),
                ('languages', models.ManyToManyField(related_name='projects', to='projects.language')),
                ('members', models.ManyToManyField(related_name='member_of_projects', to='profiles.profiles')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to='profiles.profiles')),
            ],
        ),
    ]
