# Generated by Django 6.0.1 on 2026-01-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Python', 'Python Community'), ('JavaScript', 'JavaScript Community'), ('Java', 'Java Community'), ('C++', 'C++ Community'), ('C#', 'C# Community'), ('Go', 'Go Community'), ('Rust', 'Rust Community'), ('Ruby', 'Ruby Community'), ('PHP', 'PHP Community'), ('Swift', 'Swift Community'), ('Kotlin', 'Kotlin Community'), ('TypeScript', 'TypeScript Community'), ('R', 'R Community'), ('C', 'C Community')], default='Python', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('about_info', models.TextField(default='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=255)),
                ('email_id', models.EmailField(default='unknown@gmail.com', max_length=254, null=True)),
                ('followers', models.PositiveBigIntegerField(default=0)),
                ('projects', models.PositiveIntegerField(default=0)),
                ('email_verified', models.BooleanField(default=False)),
                ('login_status', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('profile_picture', models.TextField(blank=True, null=True)),
                ('jobTitle', models.TextField(blank=True, null=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.community')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(default=0)),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='profiles.profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('Received message', 'RM'), ('Follwed You', 'FU'), ('Logged in', 'LI')], max_length=255)),
                ('detail', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('done_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performed_activities', to='profiles.profiles')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.profiles')),
            ],
        ),
    ]
