# Generated by Django 6.0.1 on 2026-01-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profiles_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blocked_by', to='profiles.profiles'),
        ),
    ]
