# Generated by Django 6.0.1 on 2026-03-28 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profiles_blacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='active_notifications',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
