# Generated by Django 6.0.1 on 2026-04-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profiles_active_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
