# Generated by Django 6.0.1 on 2026-04-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profiles_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/blank_profile.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
