# Generated by Django 6.0.1 on 2026-03-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_likes_alter_like_post_like_unique_like'),
        ('profiles', '0006_profiles_active_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liked_post', to='profiles.profiles'),
        ),
    ]
