# Generated by Django 6.0.1 on 2026-05-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
