# Generated by Django 6.0.1 on 2026-01-24 12:13

import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file_name',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='path',
            field=models.FileField(upload_to=inbox.models.upload_file_path),
        ),
    ]
