# Generated by Django 6.0.1 on 2026-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_message_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='message',
        ),
        migrations.AddField(
            model_name='attachment',
            name='messages',
            field=models.ManyToManyField(related_name='attachement', to='inbox.message'),
        ),
    ]
