# Generated by Django 6.0.1 on 2026-03-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0007_rename_messages_attachment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='attachement', to='inbox.message'),
        ),
    ]
