# Generated by Django 6.0.1 on 2026-05-03 13:50

import inbox.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0008_alter_attachment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inbox.models.upload_file_path),
        ),
    ]
